#!/bin/bash
[ "$UID" -eq 0 ] || { echo "This script must be run as root."; exit 1;}

udevrule=/etc/udev/rules.d/80-keychron.rules
modprobeconf=/etc/modprobe.d/hid_apple.conf

if [ -f $udevrule ]; then
    rm $udevrule
fi
echo 'SUBSYSTEMS=="input", ATTRS{name}=="Keychron K2", RUN+="echo 0 | tee /sys/module/hid_apple/parameters/fnmode"' >> $udevrule
udevadm control --reload-rules && sudo udevadm trigger

if [ -f $modprobeconf ]; then
    rm $modprobeconf
fi
echo 'options hid_apple fnmode=0' >> $modprobeconf
#echo 0 | sudo tee /sys/module/hid_apple/parameters/fnmode
echo all done
